export enum ModalActions {
  InviteCollaborators = 'invite-modal',
  InviteViewers = 'invite-viewers-modal',
  SignNowOwner = 'sign-now-owner',
  Cancel = 'cancel-modal',
  Decline = 'decline-modal',
  ChangeTitle = 'change-title',
  ShowHistory = 'history-modal',
  SignNow = 'sign-now',
  Manage = 'show-manage-modal',
  ManageViewers = 'manage-viewers-modal',
  GetSignature = 'get-signature',
  ShowFinaliseWarning = 'show-owner-finalise-warning-modal',
  PayChoosePaymentMethod = 'pay-choose-payment-method',
  ShowPaymentPayNow = 'show-payment-pay-now-modal',
  Edit = 'edit-modal',
  StartDocumentEdit = 'start-doc-edit',
  ExportDocument = 'show-export-document-modal',
  ShowPaymentCreatorModal = 'show-payment-creator-modal',
  ShowPaymentPayerModal = 'show-payment-payer-modal',
  ShowPaymentSelectRoleModal = 'show-payment-select-role-modal',
  ShowPaymentStatusModal = 'show-payment-status-modal',
  ShowKYCVerify = 'show-kyc-verify-modal',
  AddSignerDataModal = 'add-signer-data-modal',
  AddAnotherSigner = 'add-another-signer',
  ShowPlaid = 'paymentsPlaidModal',
  RemoveSignature = 'remove-signature-modal',
}
